---
Description: Deploy an Elastic Beanstalk app stored in CodeCommit via CodePipeline.
  **WARNING** This template creates one or more Amazon EC2 instances and a CodePipeline
  pipeline. You will be billed for the AWS resources used if you create a stack from
  this template.
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  RepositoryName:
    Description: The name of your CodeCommit repo. Go to https://console.aws.amazon.com/codecommit.
    Type: String
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Can contain only ASCII characters.
    Default: my-nodejs-app
  RepositoryBranch:
    Description: The name of the branch for the CodeCommit repo
    Type: String
    Default: master
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Can contain only ASCII characters.
  VPCId:
    Description: VPC ID of the Lab VPC
    Type: AWS::EC2::VPC::Id
    AllowedPattern: .+
  Subnets:
    Description: Subnets of EC2 instances
    Type: List<AWS::EC2::Subnet::Id>
    AllowedPattern: .+
  Ec2KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    ConstraintDescription: must be the name of an existing EC2 KeyPair
    AllowedPattern: .+
  AutoScalingMinInstanceCount:
    Description: Minimum number of EC2 instances for Auto Scaling
    Type: String
    Default: 1
    ConstraintDescription: Specify a number between 1 - 20
  AutoScalingMaxInstanceCount:
    Description: Maximum number of EC2 instances for Auto Scaling
    Type: String
    Default: 2
    ConstraintDescription: Specify a number between 1 - 20
  Ec2InstanceType:
    Description: The instance type for the dev environment
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: t2.micro
  SSLCertificateArn:
    Description: The SSL/TLS certificate ARN
    Type: String
    MinLength: 0
    MaxLength: 2048
    Default: ""
Conditions:
  TlsEnabled: !Not [ !Equals [ !Ref SSLCertificateArn, "" ] ]
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: CodeCommit Repository
      Parameters:
      - RepositoryName
      - RepositoryBranch
    ParameterLabels:
      RepositoryName:
        default: CodeCommit Repository Name
      RepositoryBranch:
        default: CodeCommit Repository Branch
Resources:
  ElasticBeanstalkServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
          "Statement": [{
            "Effect": "Allow",
            "Principal": { "Service": [ "elasticbeanstalk.amazonaws.com" ]},
            "Action": [ "sts:AssumeRole" ]
          }]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkService

  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP traffic from load balancer only
      VpcId:
        Ref: VPCId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        SourceSecurityGroupId:
          Ref: LoadBalancerSecurityGroup
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP only
      VpcId:
        Ref: VPCId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0

  Ec2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      RoleName:
        Fn::Join:
          - "-"
          - - Ref: AWS::StackName
            - ec2-role

  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: Ec2Role

  nodeApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS Elastic Beanstalk Sample Application
  nodeApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: nodeApplication
      Description: AWS ElasticBeanstalk Sample Application Version
      SourceBundle:
        S3Bucket:
          Fn::Join:
          - "-"
          - - elasticbeanstalk-samples
            - Ref: AWS::Region
        S3Key: nodejs-sample.zip
  nodeConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: nodeApplication
      Description: AWS ElasticBeanstalk Sample Configuration Template
      OptionSettings:
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: !Ref AutoScalingMinInstanceCount

        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: !Ref AutoScalingMaxInstanceCount

        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced
        
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: LoadBalancerType
          Value: application

        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value: !Ref ElasticBeanstalkServiceRole

        - Namespace: aws:ec2:vpc
          OptionName: VPCId
          Value: !Ref VPCId

        - Namespace: aws:ec2:vpc
          OptionName: Subnets
          Value:
            Fn::Join:
              - ","
              - !Ref Subnets

        - Namespace: aws:ec2:vpc
          OptionName: ELBSubnets
          Value:
            Fn::Join:
              - ","
              - !Ref Subnets

        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: !Ref Ec2InstanceType
        
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref Ec2InstanceProfile

        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: SecurityGroups
          Value:
            - - Ec2SecurityGroup

        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: EC2KeyName
          Value: !Ref Ec2KeyPairName

        - Namespace: aws:autoscaling:updatepolicy:rollingupdate
          OptionName: RollingUpdateEnabled
          Value: true

        - Namespace: aws:autoscaling:updatepolicy:rollingupdate
          OptionName: RollingUpdateType
          Value: Health

        - Namespace: aws:autoscaling:trigger
          OptionName: MeasureName
          Value: CPUUtilization

        - Namespace: aws:autoscaling:trigger
          OptionName: Unit
          Value: Percent

        - Namespace: aws:autoscaling:trigger
          OptionName: UpperThreshold
          Value: 80

        - Namespace: aws:autoscaling:trigger
          OptionName: LowerThreshold
          Value: 40

        - Namespace: aws:elbv2:listener:default
          OptionName: ListenerEnabled
          Value: !If [ TlsEnabled, false, true ]

        - Namespace: aws:elbv2:loadbalancer
          OptionName: SecurityGroups
          Value:
            - - !Ref LoadBalancerSecurityGroup            

        - Namespace: aws:elbv2:loadbalancer
          OptionName: ManagedSecurityGroup
          Value:
            - - !Ref LoadBalancerSecurityGroup

        - Namespace: aws:elbv2:listenerrule:default
          OptionName: PathPatterns
          Value: "/*"
        
        - Namespace: !Sub
          - "aws:elbv2:listener:${ListenPort}"
          - ListenPort: !If [ TlsEnabled, 443, 80 ]
          OptionName: Protocol
          Value: !If [ TlsEnabled, HTTPS, HTTP ]

        - Namespace: !Sub
          - "aws:elbv2:listener:${ListenPort}"
          - ListenPort: !If [ TlsEnabled, 443, 80 ]
          OptionName: Rules
          Value: default

        - Namespace: !Sub
          - "aws:elbv2:listener:${ListenPort}"
          - ListenPort: !If [ TlsEnabled, 443, 80 ]
          OptionName: SSLCertificateArns
          Value: !Ref SSLCertificateArn

      SolutionStackName: 64bit Amazon Linux 2018.03 v4.9.0 running Node.js
  nodeEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    DependsOn:
    - nodeApplication
    - nodeConfigurationTemplate
    - nodeApplicationVersion
    Properties:
      ApplicationName:
        Ref: nodeApplication
      Description: AWS ElasticBeanstalk Sample Node Environment
      TemplateName:
        Ref: nodeConfigurationTemplate
      VersionLabel:
        Ref: nodeApplicationVersion
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: codepipeline-service
        PolicyDocument:
          Statement:
          - Action:
            - codecommit:GetBranch
            - codecommit:GetCommit
            - codecommit:UploadArchive
            - codecommit:GetUploadArchiveStatus
            - codecommit:CancelUploadArchive
            Resource: "*"
            Effect: Allow
          - Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:GetBucketVersioning
            Resource: "*"
            Effect: Allow
          - Action:
            - s3:PutObject
            Resource:
            - arn:aws:s3:::codepipeline*
            - arn:aws:s3:::elasticbeanstalk*
            Effect: Allow
          - Action:
            - codedeploy:CreateDeployment
            - codedeploy:GetApplicationRevision
            - codedeploy:GetDeployment
            - codedeploy:GetDeploymentConfig
            - codedeploy:RegisterApplicationRevision
            Resource: "*"
            Effect: Allow
          - Action:
            - elasticbeanstalk:*
            - ec2:*
            - elasticloadbalancing:*
            - autoscaling:*
            - cloudwatch:*
            - s3:*
            - sns:*
            - cloudformation:*
            - rds:*
            - sqs:*
            - ecs:*
            - iam:PassRole
            Resource: "*"
            Effect: Allow
          - Action:
            - lambda:InvokeFunction
            - lambda:ListFunctions
            Resource: "*"
            Effect: Allow
          Version: '2012-10-17'
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
  CodePipelineStack:
    Type: AWS::CodePipeline::Pipeline
    DependsOn:
    - nodeApplication
    - nodeEnvironment
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
      - Name: Source
        Actions:
        - InputArtifacts: []
          Name: Source
          ActionTypeId:
            Category: Source
            Owner: AWS
            Version: '1'
            Provider: CodeCommit
          OutputArtifacts:
          - Name: MyApp
          Configuration:
            BranchName:
              Ref: RepositoryBranch
            RepositoryName:
              Ref: RepositoryName
          RunOrder: 1
      - Name: Beta
        Actions:
        - InputArtifacts:
          - Name: MyApp
          Name: EbApp
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: '1'
            Provider: ElasticBeanstalk
          OutputArtifacts: []
          Configuration:
            ApplicationName:
              Ref: nodeApplication
            EnvironmentName:
              Ref: nodeEnvironment
          RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
Outputs:
  AppURL:
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - nodeEnvironment
          - EndpointURL
        - "/"
    Description: URL for the working Node application
  CodePipelineURL:
    Value:
      Fn::Join:
      - ''
      - - https://console.aws.amazon.com/codepipeline/home?region=
        - Ref: AWS::Region
        - "#/view/"
        - Ref: CodePipelineStack
    Description: Pipeline URL
  nodeApplication:
    Value:
      Ref: nodeApplication
  nodeApplicationVersion:
    Value:
      Ref: nodeApplicationVersion
    Description: The Elastic Beanstalk application
  nodeConfigurationTemplate:
    Value:
      Ref: nodeConfigurationTemplate
    Description: The Elastic Beanstalk configuration
  nodeEnvironment:
    Value:
      Ref: nodeEnvironment
    Description: The Elastic Beanstalk environment on which the application runs
  CodePipelineRole:
    Value:
      Ref: CodePipelineRole
    Description: The IAM role associated with CodePipeline pipeline